AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/**/*
    - bin/*

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/services/**/*
