AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/**/*
    - bin/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/services/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - db/**/*
